import Colors from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const authstyles = StyleSheet.create({
  main: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    height: "100%",
    paddingHorizontal: 10,
    maxWidth: 500,
    width: "100%",
    alignSelf: "center",
    overflow: "scroll",
    // borderWidth: 4,
  },
  authIcon: {
    backgroundColor: "#d3d3d3",
    padding: 10,
    paddingHorizontal: 13,
    borderRadius: 5,
  },
  btn: {
    marginTop: 25,
    width: "100%",
    display: "flex",
    alignContent: "center",
    justifyContent: "center",
    paddingVertical: 17,
    backgroundColor: Colors.light.primary,
    borderRadius: 10,
    shadowColor: Colors.light.primary,
    shadowOffset: {
      width: 0,
      height: 20,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  inpt: {
    borderWidth: 1,
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 9,
    borderColor: Colors.light.primary,
    backgroundColor: Colors.light.lightBlue,
    marginTop: 25,
    position: "relative",
  },
  forget: {
    fontSize: 12,
    fontWeight: "700",
    alignSelf: "flex-end",
    color: Colors.light.primary,
    marginTop: 10,
  },
  authmaincontainer: {
    marginTop: 50,
    display: "flex",
    gap: 20,
    paddingHorizontal: 20,
    alignItems: "center",
    width: "100%",
  },
  authsubcontainer: {
    width: "70%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  forgetcontainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    alignSelf: "flex-end",
    width: "100%",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",

    paddingTop: 15,
    width: "100%",
  },
  subtitle: {
    marginTop: 15,
    fontSize: 19,
    maxWidth: 220,
    fontWeight: "500",
    textAlign: "center",
  },
  title: {
    marginTop: 30,
    fontSize: 23,
    fontWeight: "700",
    color: Colors.light.primary,
  },
  errorText: {
    color: "red",
    width: "100%",
    marginLeft: 9,
    paddingTop: 3,
    // position: "absolute",
    // top: 2,
    // right: 3,
  },
});
